server:
  port: 8088
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  application:
    name: tablego-springboot
  main:
    allow-bean-definition-overriding: true
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.49.28:1521:orcl
    username: test3_trunk
    password: test456
#    hikari:
#      minimum-idle: 1
#      maximum-pool-size: 10
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: 0
      logic-not-delete-value: 1
      where-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
swagger:
  title: ${spring.application.name}
  description: "@project.description@API文档"
  version: 1.0.0
  enabled: true
  contact:
    name: bianj
    email: tablego@qq.com
    url: http://www.tablego.cn
  base-package: cn.tablego.project.springboot.controller
