package cn.tablego.project.springboot.model;

import javax.validation.constraints.NotBlank;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import cn.tablego.project.springboot.common.model.OverrideBeanMethods;

/**
 * 系统菜单表(TSYS_MENU)
 *
 * @author bianj
 * @version 1.0.0 2021-12-07
 */
@Setter
@Getter
@Accessors(chain = true)
@ApiModel(description = "系统菜单表")
@TableName("TSYS_MENU")
public class TsysMenu extends OverrideBeanMethods {
    /** 版本号 */
    private static final long serialVersionUID = -7157415547042524648L;

    /** 创建系统菜单表实例对象 */
    public static TsysMenu newInstance() {
        return new TsysMenu();
    }

    /* This code was generated by TableGo tools, mark 1 begin. */

    @ApiModelProperty(value = "用于表示菜单英文代码,代码与生命周期组成唯一索引Studio需显示文本输入", position = 1)
    @JsonProperty(index = 1)
    @TableId
    private String menuCode;

    @ApiModelProperty(value = "分类编号", position = 2)
    @JsonProperty(index = 2)
    private String kindCode;

    @ApiModelProperty(value = "交易编号", position = 3)
    @JsonProperty(index = 3)
    private String transCode;

    @ApiModelProperty(value = "一个来源URL实体模型、关联模型、视图模型、查询模型、单一查询模板、操作模型、工作流模型的入口地址、用户自定义URL、js入口", position = 4)
    @JsonProperty(index = 4)
    private String subTransCode;

    @ApiModelProperty(value = "用于表示菜单中文名称Studio需显示文本输入", position = 5)
    @JsonProperty(index = 5)
    @NotBlank(message = "用于表示菜单中文名称Studio需显示文本输入不能为空！")
    private String menuName;

    @ApiModelProperty(value = "菜单参数", position = 6)
    @JsonProperty(index = 6)
    private String menuArg;

    @ApiModelProperty(value = "名称之前ICON图标或者菜单的背景图片", position = 7)
    @JsonProperty(index = 7)
    private String menuIcon;

    @ApiModelProperty(value = "", position = 8)
    @JsonProperty(index = 8)
    private String menuUrl;

    @ApiModelProperty(value = "用于表示点击菜单后展现页面的显示方式取数据字典[SYS_BIZ_WINDOW_CATE]0-工作区TAB页1-弹出窗口", position = 9)
    @JsonProperty(index = 9)
    private String windowType;

    @ApiModelProperty(value = "用于表示单例窗口\\每次打开新窗口模式", position = 10)
    @JsonProperty(index = 10)
    private String windowModel;

    @ApiModelProperty(value = "对菜单功能的简单描述，鼠标悬停在菜单名称上时可做相应的提示", position = 11)
    @JsonProperty(index = 11)
    private String tip;

    @ApiModelProperty(value = "快捷键", position = 12)
    @JsonProperty(index = 12)
    private String hotKey;

    @ApiModelProperty(value = "用于表示菜单上级节点的引用Studio需显示节点选择输入", position = 13)
    @JsonProperty(index = 13)
    private String parentCode;

    @ApiModelProperty(value = "用于表示同级菜单下的顺序排列Studio需显示", position = 14)
    @JsonProperty(index = 14)
    private Integer orderNo;

    @ApiModelProperty(value = "用于表示该菜单是否默认展开取数据字典[SYS_BIZ_YES_OR_NO]0-否1-是", position = 15)
    @JsonProperty(index = 15)
    private String openFlag;

    @ApiModelProperty(value = "用于表示菜单各级之间关系,取各级菜单id前后加'#'号e.g. #grandfather#father#children#", position = 16)
    @JsonProperty(index = 16)
    private String treeIdx;

    @ApiModelProperty(value = "备注", position = 17)
    @JsonProperty(index = 17)
    private String remark;

    /* This code was generated by TableGo tools, mark 1 end. */
}