package cn.tablego.project.springboot.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import cn.tablego.project.springboot.common.model.OverrideBeanMethods;

/**
 * 角色权限授权表(TSYS_ROLE_RIGHT)
 *
 * @author bianj
 * @version 1.0.0 2021-12-07
 */
@Setter
@Getter
@Accessors(chain = true)
@ApiModel(description = "角色权限授权表")
@TableName("TSYS_ROLE_RIGHT")
public class TsysRoleRight extends OverrideBeanMethods {
    /** 版本号 */
    private static final long serialVersionUID = -1808010871437595086L;

    /** 创建角色权限授权表实例对象 */
    public static TsysRoleRight newInstance() {
        return new TsysRoleRight();
    }

    /* This code was generated by TableGo tools, mark 1 begin. */

    @ApiModelProperty(value = "交易编号", position = 1)
    @JsonProperty(index = 1)
    @TableId
    private String transCode;

    @ApiModelProperty(value = "子交易编号", position = 2)
    @JsonProperty(index = 2)
    private String subTransCode;

    @ApiModelProperty(value = "授权角色", position = 3)
    @JsonProperty(index = 3)
    private String roleCode;

    @ApiModelProperty(value = "分配人", position = 4)
    @JsonProperty(index = 4)
    private String createBy;

    @ApiModelProperty(value = "分配时间", position = 5)
    @JsonProperty(index = 5)
    private Integer createDate;

    @ApiModelProperty(value = "生效时间", position = 6)
    @JsonProperty(index = 6)
    private Integer beginDate;

    @ApiModelProperty(value = "失效时间", position = 7)
    @JsonProperty(index = 7)
    private Integer endDate;

    @ApiModelProperty(value = "用于表示该授权的操作授权标志取数据字典[SYS_BIZ_RIGHT_FLAG]1-操作2-授权", position = 8)
    @JsonProperty(index = 8)
    private String rightFlag;

    @ApiModelProperty(value = "用于表示该授权的是否禁止标志取数据字典[SYS_BIZ_RIGHT_ENABLE]0-禁止1-可用", position = 9)
    @JsonProperty(index = 9)
    private String rightEnable;

    /* This code was generated by TableGo tools, mark 1 end. */
}