package cn.tablego.project.springboot.model;

import com.baomidou.mybatisplus.annotation.TableField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import cn.tablego.project.springboot.common.model.OverrideBeanMethods;

/**
 * 系统子交易表(TSYS_SUBTRANS)
 *
 * @author bianj
 * @version 1.0.0 2021-12-07
 */
@Setter
@Getter
@Accessors(chain = true)
@ApiModel(description = "系统子交易表")
@TableName("TSYS_SUBTRANS")
public class TsysSubtrans extends OverrideBeanMethods {
    /** 版本号 */
    private static final long serialVersionUID = 2500514590198412091L;

    /** 创建系统子交易表实例对象 */
    public static TsysSubtrans newInstance() {
        return new TsysSubtrans();
    }

    /* This code was generated by TableGo tools, mark 1 begin. */

    @ApiModelProperty(value = "交易编号", position = 1)
    @JsonProperty(index = 1)
    @TableId
    private String transCode;

    @ApiModelProperty(value = "子交易编号", position = 2)
    @JsonProperty(index = 2)
    private String subTransCode;

    @ApiModelProperty(value = "子交易名称", position = 3)
    @JsonProperty(index = 3)
    private String subTransName;

    @ApiModelProperty(value = "映射服务", position = 4)
    @JsonProperty(index = 4)
    private String relServ;

    @ApiModelProperty(value = "00-不控制功能权限/不控制数据权限01-不控制功能权限/控制数据权限10-控制功能权限/不控制数据权限11-控制功能权限/控制数据权限", position = 5)
    @JsonProperty(index = 5)
    private String relUrl;

    @ApiModelProperty(value = "0-不控制1-授权控制", position = 6)
    @JsonProperty(index = 6)
    private String ctrlFlag;

    @ApiModelProperty(value = "0-否1-是", position = 7)
    @JsonProperty(index = 7)
    private String loginFlag;

    @ApiModelProperty(value = "备注", position = 8)
    @JsonProperty(index = 8)
    private String remark;

    @ApiModelProperty(value = "扩展字段1", position = 9)
    @JsonProperty(index = 9)
    @TableField(value = "EXT_FIELD_1")
    private String extField1;

    @ApiModelProperty(value = "扩展字段2", position = 10)
    @JsonProperty(index = 10)
    @TableField(value = "EXT_FIELD_2")
    private String extField2;

    @ApiModelProperty(value = "扩展字段3", position = 11)
    @JsonProperty(index = 11)
    @TableField(value = "EXT_FIELD_3")
    private String extField3;

    /* This code was generated by TableGo tools, mark 1 end. */
}